### ISSUE TITLE
[Feature] Longer duration of a task

### ISSUE THREAD

**Issue by frost1161** [StaySortedHQ/reports#22]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Set the duration of a task for longer than 48 hours. 

**Describe alternatives you've considered**
Create events instead of a task.

**Reported by:**
 - user name: 周恩铭 
 - contact method: zhouenming1234@126.com
 - reference: https://app.frontapp.com/open/msg_eyy7ryv

**Comment by leotumwattana** [comment]
@frost1161: 

Noted on the user request, but this is not likely something we will do due to principles of task/time management. 

I would recommend suggesting to the requester you break up any tasks that are over 3 hours into smaller chunks. Chunks that can be completed in one go. 

There are couple of benefits to breaking up large tasks:

1. Doing so helps digest what steps that task really requires of you in more detail. In short, it ensures you think the task through. 

The following phrase comes to mind: "How do you eat an elephant? One bite at a time."

2. A single large task that spans over a day means you can no longer schedule anything in between. Which isn't realistic. For example you still need to leave time for food, rest and other stuff in between. So if anything, we might reduce the maximum duration to below 24 hours. 🤣

Hope that helps the user and gives us good written insight into the concept of hyper scheduling.

**Comment by frost1161** [comment]
Got it. Thank you, I will pass this on to the user to elaborate on it. I did explain to the person to use events.
